name: DigitalOcean App Platform deployment

on:
  workflow_run:
    workflows: ["Docker"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@v1.1.5
        with:
          app_name: goldfish-app
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
