name: DigitalOcean App Platform deployment
  
on:
  workflow_run:
    workflows: ["Docker"]
    types:
      - completed

jobs:
  deploy:
    uses: digitalocean/app_action@v1.1.5
    with:
      app_name: my_DO_app
      token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
